#%RAML 1.0 DataType

# missing from correct answer
displayName: Account
description: Defines the fields in Account Datatype
# missing correct answer

type: object
properties: 
  ID?: integer
  firstName: string
  lastName: string
  address: string
  postal: string
  country: string
  miles: integer
  creationDate: datetime
  type: string
